import { useEffect, useState } from "react";

export const VIEWS = [
  {v: "plant", label: "Plant"},
  {v: "dataops", label: "Data Ops", n: "Q1"},
  {v: "ask", label: "Ask", n: "Q2"},
  {v: "docs", label: "Documents"},
  {v: "asset", label: "Asset 360", n: "Q3"},
  {v: "memory", label: "Failure Memory", n: "Q3"},
];

export default function Header({hub, aiState, view, setView}){
  const [now, setNow] = useState(new Date());
  useEffect(() => { const t = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(t); }, []);
  const ai = aiState === "live" ? ["ok", "AI answers: live"] : aiState === "connecting" ? ["warn pulse", "AI answers: connecting…"] : ["", "AI answers: offline, retrieval mode"];
  return (
    <header className="top">
      <div className="topin">
        <div className="brand">
          <svg width="30" height="30" viewBox="0 0 30 30" aria-hidden="true"><rect x="1" y="1" width="28" height="28" rx="6" fill="var(--accent)"/><circle cx="10" cy="11" r="3" fill="none" stroke="var(--accent-ink)" strokeWidth="2"/><circle cx="21" cy="11" r="3" fill="none" stroke="var(--accent-ink)" strokeWidth="2"/><circle cx="15.5" cy="21" r="3" fill="none" stroke="var(--accent-ink)" strokeWidth="2"/><path d="M13 11h5M11.6 13.6l2.6 4.6M19.4 13.6l-2.6 4.6" stroke="var(--accent-ink)" strokeWidth="2"/></svg>
          <div><b>Plant Knowledge Hub</b><span>SDK Polyolefin · LLDPE Unit</span></div>
        </div>
        <div className="topmeta">
          <span className="chip"><span className="dot ok"></span><span>{hub ? `${hub.docs.length} docs · ${hub.wos.length} work orders · ${hub.index.chunks.length} passages indexed` : "Loading…"}</span></span>
          <span className="chip" title={aiState === "live" ? "Answers are generated by Claude from the retrieved sources only." : "Set ANTHROPIC_API_KEY on the server (api/ask.js) for live answers."}><span className={"dot " + ai[0]}></span><span>{ai[1]}</span></span>
          <span className="chip mono tnum">{now.toLocaleString("en-GB", {weekday: "short", hour: "2-digit", minute: "2-digit", second: "2-digit"})}</span>
        </div>
      </div>
      <nav className="tabs" role="tablist">
        {VIEWS.map(x => <button key={x.v} className="tab" role="tab" aria-selected={view === x.v} onClick={() => setView(x.v)}>{x.label}{x.n && <span className="n">{x.n}</span>}</button>)}
      </nav>
    </header>
  );
}
