// Suggested questions and their verified answers (used when live AI is unavailable)
export const SUGG = [
  "GA-1201A vibration is at 5.3 mm/s and rising. What should I check first, and how close are we to a trip?",
  "What happens when VSHH-1201 trips GA-1201A?",
  "What are the alignment targets for GA-1201A and when do I do a hot check?",
  "What seal flush differential pressure is needed before starting GA-1201A?",
  "Which gasket and box-up failures have we had across the plant?"
];
// Verified answers for the scripted questions (used when generative AI is unavailable)
export const CURATED = {
  [SUGG[0]]: {answer:"Treat this as a developing bearing or alignment fault, not a nuisance alarm. Vibration is 5.3 mm/s against a 4.5 mm/s alarm and a 7.1 mm/s trip [LIVE-GA-1201A][OPL-GA-1201A-07], and it has risen far more than the 1 mm/s-per-week threshold that calls for a planned bearing inspection [OPL-GA-1201A-07]. The same pattern preceded the Feb 2025 trip, which was traced to angular misalignment after foundation settlement [WO-240003].",
    steps:["Correlate VT-1201 with TT-1201 bearing temperature and check whether the 1x running-speed component dominates; escalate to the reliability engineer if it does [OPL-GA-1201A-07]","Check the oil bath sits at the middle of the sight glass with ISO VG 68, since over- or under-fill also heats the bearing [OPL-GA-1201A-02]","Prepare a controlled changeover to GA-1201B. At 7.1 mm/s (1oo2) the safety PLC trips the motor, closes XV-1201, opens FV-1201 and auto-starts GA-1201B [TJC-LLD-IL-GA-1201A]","Once on standby, laser-check alignment to < 0.05 mm/100 mm angular and < 0.05 mm offset, then do a hot check after about 2 h at temperature [OPL-GA-1201A-03][OPL-GA-1201A-05]","Inspect the baseplate grout and DE bearing 7310 BECBM, which failed after the last misalignment episode [WO-240013][WO-240004]"],
    confidence:88, reason:"Thresholds come from the approved OPL and Rev 3 interlock matrix, and three past work orders on this tag show the same failure path.", cautions:[]},
  [SUGG[1]]: {answer:"VSHH-1201 trips on bearing vibration above 7.1 mm/s RMS with 1oo2 voting [TJC-LLD-IL-GA-1201A]. The safety PLC then trips the GA-1201A motor, closes discharge valve XV-1201, opens the min-flow valve FV-1201, annunciates on the DCS and auto-starts standby pump GA-1201B [TJC-LLD-IL-GA-1201A]. The trip is latched and needs a manual reset once the cause has cleared and permissives are healthy [TJC-LLD-IL-GA-1201A].",
    steps:["Before restart, all permissives must be true: suction valve open (ZSO-1201), seal flush dP above 1.5 bar (PDI-1201), min-flow valve open (ZSO-1202) and DCS reset done [TJC-LLD-IL-GA-1201A]","The last real VSHH-1201 trip, at 7.4 mm/s, was caused by angular misalignment of 0.12 mm/100 mm [WO-240003]"],
    confidence:92, reason:"Directly stated in the Rev 3 cause and effect matrix for SEQ-1201 (SIL 1).", cautions:["Trip set points in the source matrix are marked as dummy training values. Confirm against the live SIS configuration."]},
  [SUGG[2]]: {answer:"Target angular misalignment below 0.05 mm/100 mm and offset below 0.05 mm, measured with a laser kit at 0, 90, 180 and 270 degrees and corrected by shimming the motor feet [OPL-GA-1201A-03]. For hexane service, the cold alignment must include the thermal-growth offset, then a hot check is done on the coupling after about 2 hours at temperature [OPL-GA-1201A-05].",
    steps:["Log both cold and hot readings in the machine history [OPL-GA-1201A-05]","If vibration trips repeat, adjust the thermal-growth compensation [OPL-GA-1201A-05]","Misalignment is the top root cause of GA-1201A vibration trips and premature bearing and seal failures [OPL-GA-1201A-03][WO-240003][WO-240007]"],
    confidence:86, reason:"Stated in two approved OPLs and confirmed by maintenance history.", cautions:["In OPL-GA-1201A-03 the acceptance column is shifted by one row, so read targets from the Action column."]},
  [SUGG[3]]: {answer:"Seal flush differential pressure across orifice RO-1201 must be above 1.5 bar before start, and normally reads 1.5 to 2.5 bar on PDI-1201 [OPL-GA-1201A-01]. It is also a hard start permissive in the SEQ-1201 logic [TJC-LLD-IL-GA-1201A]. Low flush lets the seal faces overheat and leak hexane to atmosphere, which is what happened in Aug 2025 when RO-1201 was partly plugged [WO-240002].",
    steps:["If dP is low, isolate and inspect RO-1201 for plugging by polymer or dirt [OPL-GA-1201A-01]","Rule out a false reading: PDI-1201 impulse lines have fouled with hexane residue before [WO-240008]","Confirm the Plan 62 quench (N2 or steam) is lined up to the outboard side [OPL-GA-1201A-01]"],
    confidence:90, reason:"Consistent across the OPL, the interlock permissive and two work orders.", cautions:[]}
};
